%getContrast  Core pipeline for converting *.rls recordings to speckle contrast
%
%   getContrast(s,fNames) reads each laser-speckle acquisition file (*.rls)
%   generated by the in-house recorder, computes speckle-contrast frames
%   (type set by s.contrastType), forms a mean BFI image, derives a
%   data-quality mask, allows optional manual mask refinement, writes a JPEG
%   preview, and stores three MAT-files per run:
%
%       *_K_d.mat  –  SOURCE struct containing the **raw contrast cube**
%                     (X × Y × T speckle-contrast images) and a time vector
%                     in **seconds** (T × 1)
%       *_K_r.mat  –  RESULTS struct (BFI image, masks, timestamp, etc.)
%       *_K_s.mat  –  SETTINGS struct (exact copy of input parameter set *s*)
%       *_c.jpg    –  two-panel preview (BFI & final mask)
%
%   These outputs form the foundation for all downstream LSCI analyses.
%
%   INPUTS
%     s        parameter structure with fields:
%              • contrastType, contrastKernel, rawBatchSize
%              • procType, decimation
%              • minK, maxK, minI, maxI
%              • minTrust(1:3)      quality thresholds
%              • manualMask         1 = enable interactive ROI selection
%     fNames   cell array of full paths to *.rls files.
%
%   EXAMPLE
%     p = defaultContrastParams();
%     D = dir(fullfile(dataRoot,'session1','*.rls'));
%     getContrast(p, fullfile({D.folder}',{D.name}'));
%
%   DEPENDS ON
%     getContrastFromRLS, getEdgeSizeSLSCI, and other utilities in the LSCI
%     processing library.
%
%   ----------------------------------------------------------------------
%   Copyright © 2025 Dmitry D Postnov, Aarhus University
%   e-mail: dpostnov@cfin.au.dk
%   Last revision: 05-Aug-2025
%
%   Note: Header generated with ChatGPT; minor inconsistencies may remain—
%   please verify before distribution.
%   ----------------------------------------------------------------------

% %Example of s structure parametrisation
% s.libraryFolder=libraryFolder;
% % %ADJUSTED (OR VERIFIED) PER PROTOCOL - CONTRAST CALCULATION
% s.contrastType='temporal'; %'temporal' or 'spatial'
% s.contrastKernel=25; %typical values: 25 for 'temporal', 5 or 7 for 'spatial'
% s.decimFactor=25; %decimates the contrast. Output framerate = original framerate / s.decimation
% % %ADJUSTED IF NECESSARY - PERFORMANCE ADJUSTEMNTS
% s.procType='fastcpu'; %use 'fastgpu' for spatial contrast type if high-end GPU is availible, 'fastcpu' otherwise
% s.rawBatchSize=1000; %only affects processing speed, depends on availible memory (GPU and RAM)
% % %ADJUSTED IF NECESSARY - INITIAL MASKING PARAMETERS
% s.minK=0.001; %expected s.minImum contrast, unless exposure time is too long or setup is malfunctioning values below 0.001 are not expected.
% s.maxK=0.99; %anything above 1 is an artifact, for most of the applications 0.4-0.7 is expected s.maxImum.
% s.minI=10; %expected s.minImum contrast, unless exposure time is too long or setup is malfunctioning values below 0.001 are not expected.
% s.maxI=255; %anything above 1 is an artifact, for most of the applications 0.4-0.7 is expected s.maxImum.
% s.minTrust=[0.68,0.68,0.68]; %in relation of uncertain frames to the total number
% s.manualMask=0; %allows manual subselection of the area to mask
% s.decimaMethod='leaking';

function getContrast(s,fNames)

if ~all( cellfun(@(s) isempty(s) || contains(s,'.rls'), fNames(:)) )
    error('One or more *non-empty* entries do not contain ".rls".');
end

for fidx=1:1:length(fNames)
    %set file name to load data
    s.fName=char(fNames{fidx});
    clearvars results source settings

    % Launch contrast calculation from an RLS file
    [source.data,source.time,results.timeStamp,s.trustMatrix]=...
        getContrastFromRLS(s.fName,s.contrastType,'kernelSize',s.contrastKernel,'decimFactor',s.decimFactor,'decimMethod',s.decimMethod);

    imgK=squeeze(mean(source.data,3));
    imgBFI=1./(imgK.*imgK);
    results.imgI=s.trustMatrix(:,:,4);

    % Set mask
    results.mask=min(~isnan(source.data),[],3)...
        & min(source.data>s.minK,[],3)...
        & min(source.data<s.maxK,[],3)...
        & squeeze(s.trustMatrix(:,:,3))>=s.minI...
        & squeeze(s.trustMatrix(:,:,3))<=s.maxI...
        & squeeze(s.trustMatrix(:,:,1))>s.minTrust(1)...
        & squeeze(s.trustMatrix(:,:,2))>s.minTrust(2);

    h=figure;
    h.WindowState='Maximize';
    subplot(1,2,1)
    imagesc(imgBFI)
    clim([prctile(imgBFI(:),1),prctile(imgBFI(:),99)])
    axis image
    subplot(1,2,2)
    imagesc(results.mask)
    axis image
    fNameshort=split(s.fName,'\');
    fNameshort=fNameshort(end);
    if s.manualMask==1
        subplot(1,2,1)
        results.mask=results.mask & roipoly;
        hold on
        visboundaries(results.mask)
        hold off
        subplot(1,2,2)
        imagesc(results.mask)
    end
    sgtitle(strrep(fNameshort,'_',' '));
    drawnow
    print(h,strrep(s.fName,'.rls','_c.jpg'), '-djpeg', '-r300');

    % Save the settings and results
    disp('Saving the results');
    settings.contrastCalculation=s;
    results.time=source.time;
    save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_d.mat']),'source','-v7.3');
    save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_r.mat']),'results','-v7.3');
    save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_s.mat']),'settings','-v7.3');
end
end