%runContrastFromRLS  Core pipeline for converting *.rls recordings to speckle contrast
%
%   runContrastFromRLS(s,fNames) reads each laser-speckle acquisition file (*.rls)
%   generated by the in-house recorder, computes speckle-contrast frames
%   (type set by s.contrastType), forms a mean BFI image, derives a
%   data-quality mask, allows optional manual mask refinement, writes a JPEG
%   preview, and stores three MAT-files per run:
%
%       *_K_d.mat  –  SOURCE struct containing the **raw contrast cube**
%                     (X × Y × T speckle-contrast images) and a time vector
%                     in **seconds** (T × 1)
%       *_K_r.mat  –  RESULTS struct (BFI image, masks, timestamp, etc.)
%       *_K_s.mat  –  SETTINGS struct (exact copy of input parameter set *s*)
%       *_rep_contrast.jpg  –  report page: BFI & final mask
%
%   These outputs form the foundation for all downstream LSCI analyses.
%
%   INPUTS
%     s        parameter structure with fields:
%              • contrastType, contrastKernel, rawBatchSize
%              • procType, decimation
%              • trustLimitsK(1:2)  accepted contrast range
%              • trustLimitsI(1:2)  accepted intensity range
%              • minTrust(1:3)      quality thresholds
%              • manualMask         1 = enable interactive ROI selection
%     fNames   cell array of full paths to *.rls files.
%     Optional workbench hooks in s (no-op when absent): s.progressFcn(frac,label),
%     s.stageFcn(stage,detail), s.cancelFcn()->tf.
%
%   EXAMPLE
%     p = defaultContrastParams();
%     D = dir(fullfile(dataRoot,'session1','*.rls'));
%     runContrastFromRLS(p, fullfile({D.folder}',{D.name}'));
%
%   DEPENDS ON
%     getContrastFromRLS, getEdgeSizeSLSCI, and other utilities in the LSCI
%     processing library.
%
% Author: Dmitry D Postnov, CFIN, Aarhus University (dpostnov@cfin.au.dk)
% Copyright 2026 Dmitry D Postnov, Aarhus University.
% Header generation and script formatting were done with Claude Code.
% Last revision: 07-July-2026

% %Example of s structure parametrisation
% s.libraryFolder=libraryFolder;
% % %ADJUSTED (OR VERIFIED) PER PROTOCOL - CONTRAST CALCULATION
% s.contrastType='temporal'; %'temporal' or 'spatial'
% s.contrastKernel=25; %typical values: 25 for 'temporal', 5 or 7 for 'spatial'
% s.decimFactor=25; %decimates the contrast. Output framerate = original framerate / s.decimation
% % %ADJUSTED IF NECESSARY - PERFORMANCE ADJUSTEMNTS
% s.procType='fastcpu'; %use 'fastgpu' for spatial contrast type if high-end GPU is availible, 'fastcpu' otherwise
% s.rawBatchSize=1000; %only affects processing speed, depends on availible memory (GPU and RAM)
% % %ADJUSTED IF NECESSARY - INITIAL MASKING PARAMETERS

% s.minTrust=[0.68,0.68,0.68]; %in relation of uncertain frames to the total number
% s.manualMask=0; %allows manual subselection of the area to mask
% s.decimaMethod='leaking';

function runContrastFromRLS(s,fNames)

if ~all( cellfun(@(s) isempty(s) || contains(s,'.rls'), fNames(:)) )
    error('One or more *non-empty* entries do not contain ".rls".');
end

% reportOpen (Core/Reporting) owns the hook seam: the optional workbench callbacks
% are resolved to no-ops when absent and ride in rep.  s is never mutated, and
% reportSettings strips the hooks from the settings before saving.  For the manual-
% mask (roipoly) branch, cancel is only checked between files.
rep=reportOpen(s,'Contrast',fNames);

for fidx=1:1:numel(fNames)
    if reportCancelled(rep), break; end         % cooperative cancel between files
    if ~isempty(fNames{fidx})
        %set file name to load data
        s.fName=char(fNames{fidx});
        reportFile(rep,fidx,s.fName);
        clearvars results source settings

        % Launch contrast calculation from an RLS file.  The core prints its own
        % per-batch line when called without a sink; here it ticks through rep
        % instead, so the percentage rewrites one line under the banner.
        reportStage(rep,'Speckle contrast');
        [source.data,source.time,results.timeStamp,s.trustMatrix]=...
            getContrastFromRLS(s.fName,s.contrastType,'kernelSize',s.contrastKernel,'decimFactor',s.decimFactor,'decimMethod',s.decimMethod, ...
            'progressFcn',@(frac,label) reportProgress(rep,frac,label));

        imgK=squeeze(mean(source.data,3,'omitmissing'));
        imgBFI=1./(imgK.*imgK);
        results.imgI=s.trustMatrix(:,:,4);
        results.imgK=imgK;

        % Set mask
        results.mask=min(~isnan(source.data),[],3)...
            & min(source.data>=s.trustLimitsK(1),[],3)...
            & min(source.data<=s.trustLimitsK(2),[],3)...
            & squeeze(s.trustMatrix(:,:,3))>=s.trustLimitsI(1)...
            & squeeze(s.trustMatrix(:,:,3))<=s.trustLimitsI(2)...
            & squeeze(s.trustMatrix(:,:,1))>s.minTrust(1)...
            & squeeze(s.trustMatrix(:,:,2))>s.minTrust(2);

        [~,fStem,fExt]=fileparts(s.fName);      % fileparts, not split on a backslash
        fNameshort=[fStem fExt];

        % --- optional manual mask refinement, on the INTERACTIVE figure ---------
        % Shown, maximised, sized for whoever is drawing on it - and closed the
        % moment the ROI is in.  The report page below is a different object drawn
        % on a fixed canvas, which is what stops a JPEG's size being a property of
        % the operator's monitor.
        if s.manualMask==1
            hInt=figure('Name','runContrastFromRLS - refine the mask','NumberTitle','off');
            hInt.WindowState='Maximize';
            subplot(1,2,1)
            imagesc(imgBFI)
            clim([prctile(imgBFI(:),1),prctile(imgBFI(:),99)])
            axis image
            subplot(1,2,2)
            imagesc(results.mask)
            axis image
            sgtitle(strrep(fNameshort,'_',' '));
            subplot(1,2,1)
            results.mask=results.mask & roipoly;
            delete(hInt);
        end

        % --- the report page: BFI + the final mask -----------------------------
        fh=reportFigure(rep,'contrast');
        tl=tiledlayout(fh,1,2,'TileSpacing','compact','Padding','compact');
        axL=nexttile(tl);
        imagesc(axL,imgBFI)
        clim(axL,[prctile(imgBFI(:),1),prctile(imgBFI(:),99)])
        axis(axL,'image')
        if s.manualMask==1
            hold(axL,'on'); visboundaries(axL,results.mask); hold(axL,'off')
        end
        axR=nexttile(tl);
        imagesc(axR,results.mask)
        axis(axR,'image')
        sgtitle(fh,strrep(fNameshort,'_',' '));
        reportSave(rep,fh,'contrast');

        % Save the settings and results
        reportStage(rep,'Saving');
        settings.runContrastFromRLS=reportSettings(s);
        results.time=source.time;
        save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_d.mat']),'source','-v7.3');
        save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_r.mat']),'results','-v7.3');
        save(strrep(s.fName,'.rls',['_',s.contrastType(1),'_K_s.mat']),'settings','-v7.3');
        reportSaved(rep,3);
    end
end
reportClose(rep);

end